export const ADD_WATCHLIST_ITEM = 'ADD_WATCHLIST_ITEM';
export const DELETE_WATCHLIST_ITEM = 'DELETE_WATCHLIST_ITEM';
export const CHANGE_ORDER = 'CHANGE_ORDER';

export const ADD_PORTFILIO_ITEM = 'ADD_PORTFILIO_ITEM';
export const DELETE_PORTFILIO_ITEM = 'DELETE_PORTFILIO_ITEM';
export const BUY_CRYPTO = 'BUY_CRYPTO';
export const SELL_CRYPTO = 'SELL_CRYPTO';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const RESET_SETTINGS = 'RESET_SETTINGS';
